version: "3.9"

services:
  frontend:
    build: .
    container_name: vite-dev
    ports:
      - "5173:5173"          # Vite dev server
    volumes:
      - .:/app               # Монтируем локальный код в контейнер
      - /app/node_modules    # Исключаем node_modules хоста
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
